server:
  port: 8888

spring:
  config:
    activate:
      on-profile: ${ACTIVE_PROFILE:tst}
  application:
    name: config-service
  cloud:
    config:
      server:
        git: #default
          uri: https://github.com/chit-a-chat/CAC-CONFIG
        bootstrap: true

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics
encrypt:
  key-store:
    location: classpath:cac.jks
    password: ${JKS_PASSWORD}
    alias: cac